version: '3.8'
services:
  # Backend API
  backend:
    build:
      context: ./Back-end        
      dockerfile: Dockerfile
    container_name: movie-app-backend
    restart: unless-stopped
    env_file:
      - ./Back-end/.env
    environment:
      NODE_ENV: development 
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - ./Back-end:/app            
      - /app/node_modules
    networks:
      - movie-network

  # Frontend React
  frontend:
    build:
      context: ./Front-end
      dockerfile: Dockerfile
      args:
        - VITE_DOCKER_MODE=true 
        - VITE_API_URL=http://localhost:5000/api 
    container_name: movie-app-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - movie-network

# Réseau pour la communication entre services
networks:
  movie-network:
    driver: bridge